# Generated by Django 2.2.3 on 2021-06-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('img', models.CharField(max_length=100, verbose_name='图片')),
                ('view_times', models.IntegerField(default=0, verbose_name='访问量')),
                ('tag', models.IntegerField(choices=[(1, '资讯'), (2, '公司动态'), (3, '分享'), (4, '答疑'), (5, '其他')], verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='已注销', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hulaquan.Article', verbose_name='文章')),
                ('user', models.ForeignKey(default='已注销', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hulaquan.Article', verbose_name='文章')),
            ],
            options={
                'db_table': 'article_content',
            },
        ),
    ]
