# Generated by Django 2.2.3 on 2021-06-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hulaquan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecontent',
            table='hulaquan_article_content',
        ),
    ]
