# Generated by Django 2.2.3 on 2021-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hulaquan', '0002_auto_20210609_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='图片'),
        ),
    ]
