# Generated by Django 2.2.3 on 2021-06-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hulaquan', '0003_auto_20210609_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hulaquan.Article', verbose_name='文章'),
        ),
    ]
